# action.yml
name: 'Jscpd action'
description: 'Find code ducplicate copy/paste'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  path:  
    description: 'path to check'
    required: true
    default: './src'
  ignore:
    description: 'glob pattern for files what should be excluded from duplication detection'
    required: false
    default: 'gerghehzthrtjyt'
  threshold:
    description: 'threshold for duplication, in case duplications >= threshold jscpd will exit with error'
    required: false
    default: 0.1
outputs:
  output: # id of output
    description: 'The output of jscpd'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}
    - ${{ inputs.ignore }}
    - ${{ inputs.threshold }}
